---
- hosts: all
  tasks:     
    - name: list security updates
      yum:
        list: security
        
    - name: Install the security packages.
      yum:
        name: '*'
        security: yes
        state: latest


