---
- hosts: all
  tasks:          
    - name: upgrade all packages
      yum:
        name: '*'
        update_cache: yes
        state: latest
      register: reboot_required
      
    - name: restart server
      command: /usr/bin/systemd-run --on-active=5 --timer-property=AccuracySec=100ms /usr/bin/systemctl reboot
      async: 0
      poll: 0
      ignore_errors: true
      become: yes
      when: reboot_required.rc != 1

    - name: wait for server {{ ansible_ssh_host | default(inventory_hostname) }} to come back online
      wait_for:
        port: 22
        state: started
        host: '{{ ansible_ssh_host | default(inventory_hostname) }}'
        delay: 30
      delegate_to: localhost
