---
- hosts: all
  tasks:        
    - name: Install the security packages.
      yum:
        name: '*'
        security: yes
        state: latest
        register: result
        
    - debug:
        var: result

