---
- hosts: all
  tasks:          
    - name: Install the security packages.
      yum:
        name: '*'
        security: yes
        state: latest
      register: yum_list2
      
    - debug:
        var: yum_list2


