---
- hosts: all
  tasks:     
    - name: list security updates
      yum:
        list: security
      register: yum_list
      
    - debug:
        var: yum_list
        
    - name: Install the security packages.
      yum:
        name: '*'
        security: yes
        state: latest
      register: yum_list2
      
    - debug:
        var: yum_list2


